---

- name: Install Girder system dependencies
  apt:
    name: "{{ item }}"
  become: yes
  become_user: root
  with_items:
    - git
    - libffi-dev
    - build-essential
    - python2.7-dev
    - python-pip
    - libjpeg-dev
    - libssl-dev
    - zlib1g-dev

- name: Update Pip
  pip:
    name: pip
    state: latest
  become: yes
  become_user: root

- name: Download Girder
  git:
    repo: "https://github.com/girder/girder.git"
    dest: "{{ girder_path }}"
    version: "{{ girder_version }}"
    update: "{{ girder_update|default(omit) }}"
    force: "{{ girder_force|default(omit) }}"
  notify: Build Girder

- name: Install Girder Python requirements
  pip:
    requirements: "{{ girder_path }}/requirements.txt"
  become: yes
  become_user: root

- name: Install Girder and plugin requirements
  pip:
    name: ".[plugins]"
    editable: yes
    chdir: "{{ girder_path }}"
  become: yes
