---

- name: Ensure girder base directory exists
  file:
    path: "{{ girder_path }}"
    state: directory
    group: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
    mode: 0755
  become: yes
  become_user: root

- include: 1_npm/main.yml
  when: "{{ girder_web }}"

- include: 2_girder/virtualenv.yml
  when: girder_virtualenv is defined

- include: 2_girder/main.yml

- include: 2_girder/pip.yml
  when: girder_virtualenv is not defined
  become: yes
  become_user: root

- include: 2_girder/pip.yml
  when: girder_virtualenv is defined

- include: 3_daemon/main.yml
