---
- name: Prepare
  hosts: targets
  pre_tasks:
    # gpg is needed to add other APT repositories
    - name: Install gnupg2
      apt:
        name: gnupg2
        state: present
        force_apt_get: true
  roles:
    - role: girderformindlogger.girderformindlogger
      vars:
        girder_database_uri: "mongodb://mongodb:27017/girderformindlogger"
        girder_web: false
