---

- name: Build Girder web client
  environment:
    - LC_ALL: "C.UTF-8"
    - LANG: "C.UTF-8"
  command: "{{ girder_virtualenv }}/bin/girderformindlogger build"
  when: girder_web|bool

- name: Restart Girder
  systemd:
    name: girderformindlogger
    daemon_reload: true
    state: restarted
  become: true
  become_user: root
  when: girder_daemonize|bool
